name = "novelforge"
main = "server/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[vars]
CLOUDFLARE_ACCOUNT_ID = "你的account_id"
# CLOUDFLARE_API_TOKEN 不能放这里，会暴露

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "novelforge"
database_id = "3c09a004-21df-421c-856a-142ead75cdfd"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "novelforge-storage"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "novelforge-index"

[[queues.producers]]
binding = "TASK_QUEUE"
queue = "novelforge-tasks"

[[queues.consumers]]
queue = "novelforge-tasks"
max_batch_size = 5
max_batch_timeout = 10
max_retries = 3
max_concurrency = 1

# vectorize建库
# npx wrangler vectorize create novelforge-index --dimensions=1024 --metric=cosine
# ---先建库再执行语句
# npx wrangler vectorize create-metadata-index novelforge-index --property-name=novelId --type=string
# npx wrangler vectorize create-metadata-index novelforge-index --property-name=sourceType --type=string